// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieve all Rubber Ducks
	// (GET /ducks)
	GetDucks(w http.ResponseWriter, r *http.Request)
	// Store a new Rubber Duck
	// (POST /ducks)
	CreateDuck(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Retrieve all Rubber Ducks
// (GET /ducks)
func (_ Unimplemented) GetDucks(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Store a new Rubber Duck
// (POST /ducks)
func (_ Unimplemented) CreateDuck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetDucks operation middleware
func (siw *ServerInterfaceWrapper) GetDucks(w http.ResponseWriter, r *http.Request) {
	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDucks(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDuck operation middleware
func (siw *ServerInterfaceWrapper) CreateDuck(w http.ResponseWriter, r *http.Request) {
	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDuck(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ducks", wrapper.GetDucks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/ducks", wrapper.CreateDuck)
	})

	return r
}

type GetDucksRequestObject struct{}

type GetDucksResponseObject interface {
	VisitGetDucksResponse(w http.ResponseWriter) error
}

type GetDucks200JSONResponse []RubberDuck

func (response GetDucks200JSONResponse) VisitGetDucksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDucks500JSONResponse Error

func (response GetDucks500JSONResponse) VisitGetDucksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateDuckRequestObject struct {
	Body *CreateDuckJSONRequestBody
}

type CreateDuckResponseObject interface {
	VisitCreateDuckResponse(w http.ResponseWriter) error
}

type CreateDuck201JSONResponse RubberDuck

func (response CreateDuck201JSONResponse) VisitCreateDuckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateDuck400JSONResponse Error

func (response CreateDuck400JSONResponse) VisitCreateDuckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateDuck500JSONResponse Error

func (response CreateDuck500JSONResponse) VisitCreateDuckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Retrieve all Rubber Ducks
	// (GET /ducks)
	GetDucks(ctx context.Context, request GetDucksRequestObject) (GetDucksResponseObject, error)
	// Store a new Rubber Duck
	// (POST /ducks)
	CreateDuck(ctx context.Context, request CreateDuckRequestObject) (CreateDuckResponseObject, error)
}

type (
	StrictHandlerFunc    = strictnethttp.StrictHTTPHandlerFunc
	StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc
)

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetDucks operation middleware
func (sh *strictHandler) GetDucks(w http.ResponseWriter, r *http.Request) {
	var request GetDucksRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDucks(ctx, request.(GetDucksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDucks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDucksResponseObject); ok {
		if err := validResponse.VisitGetDucksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDuck operation middleware
func (sh *strictHandler) CreateDuck(w http.ResponseWriter, r *http.Request) {
	var request CreateDuckRequestObject

	var body CreateDuckJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDuck(ctx, request.(CreateDuckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDuck")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDuckResponseObject); ok {
		if err := validResponse.VisitCreateDuckResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{
	"H4sIAAAAAAAC/7xWXU/jOhD9K9bc+xj1g4+XvHG5aFVphRCrfVghHtx4WgyO7bWddgvKf1+NnY+GBkQl",
	"xFNDY8+cOefMKS9QmNIajTp4yF/AFw9Y8vh45Zxx9GCdseiCxPh1YQTSJ/7hpVUI+dlslkHYWYQcpA64",
	"Rgd1BiV6z9fDo7DQG66kYA5/V+jDBLqbPjip11DXGdBL6VBAfpe69cXuu/Nm+YhFoEbXuL2tlkt0/1fF",
	"0xhelcZ41SgDzUscfeHlc8Ktq5JA+JIrFVEIWZWQgeJuAOYN8LFB1iBoyo5N8CH4PYk7VMpsD6nLQIrB",
	"yfmYLu3Ufb1Lxb2XBfv1Zt2PE9JX7d69z5EUkH2QKLoq9coQEoG+cNIGaTTkcKHZxc2CrYxjPhjqw7gm",
	"lwUncUN/JooZceyj62SIKPe+pxKQwQadT1Xnk9lkRuMbi5pbCTmcTmaTU8jA8vAQ5ZkKqkhPawz0Qdpx",
	"grUQkMM3DLEl0NDeGu2TqiezWRJXB9TxHrdWySLenD566t9JlBazKgr0zWNZcreDHK7SAdbWJvhcVQj5",
	"Xeec3i7kjnlrgEPVk8itbnXWV1gqXjw1BU66AjfS8YCRuv52MkJ9T1qlLCHEMmAZof/rcAU5/DPtU2fa",
	"RM50bwvqTnvuHN8l6YeSf5c+MLMaCMsaklaVUrtWfRQTqnd+NOPY5l9DaRt955R3XbrBT82XClkwXUMm",
	"ksvqIQnvzZ6ydmTMhQ7oNFfMo9ugYxHUJG5Rb4PbtjFXakAIDW6NHzHmpUMesNGuSeP/jNgdyZHGbRtb",
	"Y66MZXtTHjqqsdK11I/8lZNSxhzB4fB3oB4GTXAV1gdLOD9y3CKyJtqR3xyLFuX0c6d7PdrQJvsxNliC",
	"BnFcgbOjV2DJxW0j4uEenA33IPWWz8jKyge2RGY0MrPKWZw1YylYMhYj4rO2I/07IbWtArPObKT4un2n",
	"n5q07F+46z9iU840bvdXnerVfwMAAP//bsbTWM0JAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return swagger, err
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return swagger, err
	}
	return swagger, err
}
