// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

// Defines values for NewRubberDuckSize.
const (
	NewRubberDuckSizeLarge  NewRubberDuckSize = "large"
	NewRubberDuckSizeMedium NewRubberDuckSize = "medium"
	NewRubberDuckSizeSmall  NewRubberDuckSize = "small"
)

// Defines values for RubberDuckSize.
const (
	RubberDuckSizeLarge  RubberDuckSize = "large"
	RubberDuckSizeMedium RubberDuckSize = "medium"
	RubberDuckSizeSmall  RubberDuckSize = "small"
)

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// NewRubberDuck defines model for NewRubberDuck.
type NewRubberDuck struct {
	Color string            `json:"color"`
	Name  string            `json:"name"`
	Size  NewRubberDuckSize `json:"size"`
}

// NewRubberDuckSize defines model for NewRubberDuck.Size.
type NewRubberDuckSize string

// RubberDuck defines model for RubberDuck.
type RubberDuck struct {
	Color string         `json:"color"`
	Id    int            `json:"id"`
	Name  string         `json:"name"`
	Size  RubberDuckSize `json:"size"`
}

// RubberDuckSize defines model for RubberDuck.Size.
type RubberDuckSize string

// CreateDuckJSONRequestBody defines body for CreateDuck for application/json ContentType.
type CreateDuckJSONRequestBody = NewRubberDuck
